apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: msp ##pas de tiret dans le nom du cluster
  namespace: my-log #
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  kafka:
    version: 3.3.2
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: route
        tls: true		
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: '3.3'
    storage:
      class: ibmc-vpc-block-10iops-tier
      size: 40Gi
      type: persistent-claim
  zookeeper:
    replicas: 3
    storage:
      class: ibmc-vpc-block-10iops-tier
      size: 6Gi
      type: persistent-claim	  
  entityOperator:
    topicOperator: {}
    userOperator: {}
