apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch #
  namespace: openshift-gitops #
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  version: 7.17.8
  nodeSets:
  - name: default
    count: 3
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: -Xms4g -Xmx4g
            resources:
              requests:
                memory: 8Gi
                cpu: 1
              limits:
                memory: 8Gi
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 200Gi
          storageClassName: ibmc-vpc-block-10iops-tier
    config:
      node.roles: [ "master", "data" ]
      node.store.allow_mmap: false
