apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup-redhat-logging
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
  - openshift-gitops


---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: stable-5.6
  name: cluster-logging
  source: redhat-operators 
  sourceNamespace: openshift-marketplace