apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-gitops
spec:
  channel: stable-5.6
  name: cluster-logging
  source: redhat-operators 
  sourceNamespace: openshift-marketplace